name: Publish to TestPyPI

on:
  push:
    # only run when you push a tag like "v1.2.3"
    tags:
      - 'v*.*.*'

jobs:
  build-and-publish:
    name: Build & Publish † TestPyPI
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'   # e.g. 3.10 or range '3.x'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build source & wheel
        run: python -m build

      - name: Publish to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          twine upload \
            --repository-url https://test.pypi.org/legacy/ \
            dist/*
